Edu toolkit
cloudera-labs/toolkits pull request #1
Opened 2022-06-17 20:32 UTC by wmdailey

Cloudera Labs,

I was assigned the toolkits repo to create a branch for Edu. The branch edu-toolkit contains directories for scripts, config files, notebooks, and tutorials. This should be public facing so we can ask students to download it for future practice.

Also, I created a branch for the upgrade-toolkit. I ensured all of the previous data for upgrades is there. I then gleaned back the main directory to act as a skeleton. I did edit the main ReadMe to point to the two available toolkits

2022-06-22 16:36 UTC, Chaffelson requested changes

2022-06-22 16:36 UTC, Chaffelson commented on ReadMe.md
> +# CLOUDERA EDUCATIONAL SERVICES
Please put your toolkit in its own subdir, please put a section in the root readme referring to your toolkit separately from existing toolkits

2022-06-22 16:36 UTC, Chaffelson commented on ReadMe.md
> +# CLOUDERA EDUCATIONAL SERVICES
Please remove all unnecessary dot files from your directories

2022-06-22 16:36 UTC, Chaffelson commented on bin/build_cdp_host.sh
> +validate_host
This script duplicates and conflicts with the host preparation methods in our preferred Ansible collection cloudera.cluster. Why would we maintain alternatives such as this?

2022-06-22 16:36 UTC, Chaffelson commented on bin/include.sh
> +function yes_no() {
These functions appear to be duplicates of those in build_cdp_host?

2022-06-22 16:36 UTC, Chaffelson commented on bin/mit_kerberos/manage_principals.sh
> +NUMARGS=$#
Why have singular and multiple control scripts for principals?

2022-06-22 16:36 UTC, Chaffelson commented on bin/mit_kerberos/notes_oneway_trust.txt
> +# DURING KERBEROS INSTALL WITH AMBARI
Is this out of date? Presumably we no longer need to include Ambari support

2022-06-22 16:36 UTC, Chaffelson commented on bin/mit_kerberos/notes_oneway_trust.txt
> +# Notes on setting up One-Way Trust
This notes file should instead be in docs perhaps as a guide?

2022-06-22 16:36 UTC, Chaffelson commented on bin/mit_kerberos/tutorial_install_mit_kerberos.sh
> +INSTALLING KERBEROS
This file is marked as a shell script, but reads like documentation

2022-06-22 16:36 UTC, Chaffelson commented on bin/mit_kerberos/tutorial_kerberos.txt
> +# Note. Recommend not using admin/admin, a more common name is kadmin/admin
This tutorial file shouldn't be in the bin directory, and should probably be in a separate documentation area

2022-06-22 16:36 UTC, Chaffelson commented on bin/setup_cdp_host.sh
> +function call_include() {
This appears to be a duplicate of the build_cdp_host file?

2022-06-22 16:36 UTC, Chaffelson commented on bin/setup_cm_ca.sh
> +# you may not use this file except in compliance with the License.
Ideally this would use the Ansible role with the implementation specific users etc. rather than a parallel implementation to be maintained long term?

2022-06-22 16:36 UTC, Chaffelson commented on bin/setup_cm_repo.sh
> +		sleep 3
This also duplicates a common cloudera.cluster function

2022-06-22 16:36 UTC, Chaffelson commented on bin/setup_local_repo.sh
> +	sudo rm /var/www/html/cloudera/cm7/${CM_VER}/cm${CM_VER}-redhat7.tar.gz
Assumes el7, will break. This should use the cloudera.cluster implementation which supports el7 and el8

2022-06-22 16:36 UTC, Chaffelson commented on bin/setup_zeppelin_interpreter.sh
> +	SHELLJAR=zeppelin-shell-0.8.2.7.1.7.0-551.jar
Pinned to a very specific version, is this a good idea?

2022-06-22 16:36 UTC, Chaffelson commented on conf/bashrc
> +
missing license header

2022-06-22 16:36 UTC, Chaffelson commented on conf/knox_topology/knox_logout.desktop
> +Version=1.0
This is a strange file? And it refers to Ambari

2022-06-22 16:36 UTC, Chaffelson commented on conf/s3/setup-s3-for-mounting.txt
> +
Should be a doc

2022-06-22 16:36 UTC, Chaffelson commented on conf/skel/.bashrc
> +# .bashrc
Should all these files be duplicated in /conf and /conf/skel?

2022-06-22 16:36 UTC, Chaffelson commented on conf/skel/.emacs
> +(custom-set-variables
should we include an emacs file?

2022-06-22 16:36 UTC, Chaffelson commented on conf/vimrc
> +set autoident
as with emacs, including editor configs doesn't seem like good practice

2022-06-22 16:36 UTC, Chaffelson commented on tutorial/tutorial-hive.txt
> +# Run orders.hql
Would all of these tutorials not be better as nicely formatted docs?

2022-06-29 19:44 UTC, wmdailey commented on ReadMe.md
> +# CLOUDERA EDUCATIONAL SERVICES
Created edu_student. Moved all files and directories.
Ran a find and a ls -a -R but did not find any hidden dot files to remove.

2022-06-29 19:48 UTC, wmdailey commented on bin/build_cdp_host.sh
> +validate_host
This script is part of the CDP Adm Building Clusters course. We use it to review host level requirements and to point to the Cloudera docs. Additionally, we discuss go/no-go criteria for accepting a host. I know all of this is built into Cloudera Deploy. The requirement is for a standalone tool to evaluate current state of a host. If you have a standalone playbook we can replace this script. If not I will put this onto the work list and in time we will replace it. Note - as we build out the CDP Adm Automating CDP course I am sure we will find lots of new reasons to use Ansible. I am all for moving away from shell scripts.

2022-06-29 19:50 UTC, wmdailey commented on bin/include.sh
> +function yes_no() {
The include.sh is used in many shell scripts run on cmhost. The build_cdp_host was intended to be standalone to run on remote nodes. I modified to remove the duplications. I changed the exercise to copy in the include.sh.

2022-06-29 19:53 UTC, wmdailey commented on bin/mit_kerberos/manage_principals.sh
> +NUMARGS=$#
All of the files in this directory are left over from when we use to teach MIT Kerberos. Frankly, I probably should delete the entire directory as we are now moved onto AD and IPA. However, there still may be the rare occasion where we need to teach MIT Kerberos. The multiple script uses a text file listing all of the services and users needing principals and keytabs to be created at one time. The single managed individual users.

2022-06-29 20:00 UTC, wmdailey commented on bin/mit_kerberos/notes_oneway_trust.txt
> +# DURING KERBEROS INSTALL WITH AMBARI
Absolutely way out of date with everything else in this directory. Tell you what I just deleted the entire directory and will cache this in my personal stuff.

2022-06-29 20:04 UTC, wmdailey commented on conf/skel/.bashrc
> +# .bashrc
Skel is part of the build for the host script. But this is a hold over from teaching HDP security and having to setup ssh. This is no longer required now that we are using IPA clients. The directory is now empty.

2022-06-29 20:04 UTC, wmdailey commented on conf/skel/.emacs
> +(custom-set-variables
Not required.

2022-06-29 20:04 UTC, wmdailey commented on conf/vimrc
> +set autoident
Deleted.

2022-06-29 20:07 UTC, wmdailey commented on tutorial/tutorial-hive.txt
> +# Run orders.hql
The tutorials serve two purposes. 1) These become additional assignments for subjects not covered in class. 2) and more importantly they contain command lines used by the students to copy and paste from one terminal to another. This is a work around to the pdf problem we have with students copy and pasting. As you know we are finally building a publishing system for producing HTML docs. In time I may convert these into HTML, but for now I need them in class.

2022-06-29 20:16 UTC, wmdailey commented on conf/s3/setup-s3-for-mounting.txt
> +
Moved this over to a tutorial file.

2022-06-29 20:19 UTC, wmdailey commented
I spent the last few hours cleaning this file system up. There were some amount of historical stuff carried over from HDP. I gleaned these out. This should be ready to go. Let me know if you have other requirements. WKD

2022-07-27 15:11 UTC, Chaffelson commented
Changes are looking good.
Can you please ensure that this PR does not attempt to delete the other toolkits - the purpose is to add your edu_student toolkit alongside the other ones on the `main` branch, not to have a separate branch just with edu stuff in it.
It is good to edit the top level Readme to have a section which points to the edu_student toolkit.

Once those two things are tidied up then we're good to go.

2022-08-10 22:24 UTC, wmdailey commented
Daniel,  I cloned toolkits again. I created edu-toolkit on main. I deleted the prior edu-toolkit branch. I edited the primary ReadMe.md with a short statement about edu-toolkit. There is a detailed ReadMe.md in edu-toolkit. This should meet requirements. Request pool and public release. 
WKD

2022-08-25 21:02 UTC, wmdailey commented
Edits to two files. Add functions to setup_paywall_repo.sh. Edit hosts to host in tutorial_tls_ex06.sh.

2022-08-25 23:26 UTC, closed without merging