Adding HDP discovery tool
cloudera-labs/toolkits pull request #7
Opened 2022-08-11 12:46 UTC by aravindrox

Adding discovery tool for HDP under upgrade-toolkit

2022-08-31 09:55 UTC, Chaffelson requested changes

2022-08-31 09:55 UTC, Chaffelson commented on upgrade-toolkit/HDP Discovery Tool/.gitignore
> +# Byte-compiled / optimized / DLL files
This should not be included

2022-08-31 09:55 UTC, Chaffelson commented on upgrade-toolkit/HDP Discovery Tool/LICENSE
> +                                 Apache License
This should not be included

2022-09-16 13:50 UTC, Chaffelson requested changes
Please can you remove spaces from paths

2022-09-16 15:55 UTC, aravindrox commented
Removed the spaces in root directory, Removed LICENCE and .gitignore

2022-09-16 15:55 UTC, closed without merging